/**
 * Centralized icon re-export — the single seam between Maka call sites
 * and the underlying generic UI icon library.
 *
 * Business code imports icons from `@maka/ui/icons`; this file decides
 * which icon set backs those names. Generic UI icons now come directly
 * from `lucide-react`. Bot/channel brand logos live in
 * `bot-brand-logo.tsx` because they are fixed product assets, not generic
 * UI icons.
 */

export type { LucideIcon, LucideProps } from 'lucide-react';

export {
  Accessibility,
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Brain,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  CircleCheckBig,
  CircleGauge,
  Clipboard,
  Clock,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  Download,
  Eye,
  EyeOff,
  FileCode,
  FileEdit,
  FileImage,
  FileText,
  FileType,
  Flag,
  FolderOpen,
  GitBranch,
  GitMerge,
  Globe,
  Grid3X3,
  HelpCircle,
  Hourglass,
  Info,
  KeyRound,
  Keyboard,
  LineChart,
  Loader2,
  Loader2Icon,
  MessageCircleQuestion,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreHorizontalIcon,
  MousePointer2,
  Network,
  Palette,
  PanelLeftClose,
  PanelLeftIcon,
  PanelLeftOpen,
  Paperclip,
  Pencil,
  Pin,
  PinOff,
  Plug,
  Plus,
  RefreshCcw,
  Repeat,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  SearchIcon,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Sun,
  SunMoon,
  Terminal,
  Trash2,
  User,
  Volume2,
  Wifi,
  X,
  XIcon,
} from 'lucide-react';
